### ISSUE TITLE
width on inner fields seems off

### ISSUE THREAD

**Issue by ragingdave** [64robots/nova-json#1]
I was using this with the https://github.com/Silvanite/novafieldcheckboxes field and the checkboxes get all scrunched due to w-1/2 getting applied to the inner field. I'm not sure if this is default field styling but it makes it so that larger fields are scrunched. Perhaps this should actually be fixed in the checkboxes field, but since this would be the parent element, I figured that perhaps this can be addressed here.

**Comment by beliolfa** [comment]
This style is fixed inside the `default-field` component in Nova. We are tackling this in this other package https://github.com/64robots/nova-fields.

We are rewriting all the nova fields to be customizable. So you can fix this styling issue doing something like this:

```php
use R64\NovaJson\Json;
use R64\NovaFields\Text;

Json::make('Content', [
                Text::make('Name')
                    ->fieldClasses('w-full px-8 py-6')
                    ->labelClasses('w-1/2 px-8 py-6'),
            ]),
```

In your particular case you should open an issue to that package asking for customizing styles. They could either implement this functionality or use our package instead of default wrappers
